### ISSUE TITLE
Exhibit upload page allows uploading a video file but it fails when trying to turn it into a PDF

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MotionToSingleJusticeAppeals#17]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `record appendix`
Steps to reproduce | i uploaded supporting documents, but it kept spinning and not moving toward the next page.
Expected behavior | move to the next page, and continue with the submission.
What happened instead | it frozed.
Other information | thats it.
Variable being sought | `has_evidence`
Package version | `0.1.0`

**Comment by nonprofittechy** [comment]
TODO: 

- Add some clarifying language on the upload screen that says this is meant to be printable evidence, not videos, audio, etc.
- Instead of having image/*, only let people upload image/png and image/jpeg
- Test with an iPhone to make sure the weird HEVC format can still be uploaded (try from gallery and try from a live camera upload)
